server:
  port: 9011

spring:
  profiles: ha

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/,http://localhost:8002/eureka/

feign:
  hystrix:
    enabled: true
  okhttp:
    enabled: true