version: '3'
services:
  eureka-server:
    restart: always
    build: ./eureka-server  # 创建镜像，会自动执行当前目录下eureka文件夹中的Dockerfile文件
    image: "plz821/eureka-server:v0.0.1"  # 镜像名：标签名
    hostname: eureka-server  # 注册中心的hostname一定要有，且必须和代码中配置文件里的hostname一致
    networks:
      - springcloud-docker-network  # 加入的网络，在networks节里创建
    environment:
      - TZ=Asia/Shanghai  # 设定系统的时区
    ports:
      - 8000:8000  # 映射的端口号，和代码中配置文件里的端口号一致

  provider-service:
    restart: always
    build: ./provider-service
    image: "plz821/provider-service:v0.0.1"
    networks:
      - springcloud-docker-network
    environment:
      - TZ=Asia/Shanghai
    ports:
      - 8010
    depends_on:
      - eureka-server  # 依赖的服务，其启动后才启动当前服务
    links:
      - eureka-server  # 要连接服务的名字

  consumer-service:
    restart: always
    build: ./consumer-service
    image: "plz821/consumer-service:v0.0.1"
    networks:
      - springcloud-docker-network
    environment:
      - TZ=Asia/Shanghai
    ports:
      - 9010:9010
    links:
      - eureka-server

networks:
  springcloud-docker-network:
    driver: bridge  #以桥接模式创建自定义网络，否则会使用默认的网络